name: CI for Merge on master/main

on:
  push:
    tags:
      - v*
    branches: [ master, main ]

env:
  BUILD_TYPE: prod
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}
  GKE_USER: ${{ secrets.GKE_SERVICEACCOUNT_EMAIL }}
  GKE_JSON: ${{ secrets.GKE_SERVICEACCOUNT_JSONKEY }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_PROD_CLUSTER_NAME }}
  GKE_CLUSTER_ZONE: ${{ secrets.GKE_PROD_CLUSTER_ZONE }}
  GKE_CLUSTER_PROJECT: ${{ secrets.GKE_PROD_CLUSTER_PROJECT }}
  LKE_SERVICEACCOUNT_TOKEN: ${{ secrets.LKE_SERVICEACCOUNT_TOKEN }}
  LKE_CLUSTERID: ${{ secrets.LKE_PROD_CLUSTERID }}


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Unit tests
      run: go test -short -v ./...

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  
  publish-docker:
    needs: [ build-and-test, golangci-lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare docker env
        id: fetch-docker-vars
        run: |
            chmod 700 .github/tools_install.sh
            ./.github/tools_install.sh
            IN=$(echo ${GITHUB_REPOSITORY})
            NAME=${IN#"Ubivius/"}
            VERSION=$(yq e '.version' ./chart/Chart.yaml)
            echo "::set-output name=REPO_NAME::$(echo $NAME)"
            echo "::set-output name=BRANCH::$(echo $GITHUB_REF)"
            echo "::set-output name=REPO_VERSION::$(echo $VERSION)"
        shell: bash

      - name: Build and Push Artefact to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          BUILD_TYPE: ${{ env.BUILD_TYPE }}
        with:
          name: ubiviushub/${{ steps.fetch-docker-vars.outputs.REPO_NAME }}
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_PWD }}
          buildargs: BUILD_TYPE
          dockerfile: Dockerfile
          tags: "${{ steps.fetch-docker-vars.outputs.REPO_VERSION }}"

  publish-helm:
    needs: [ build-and-test, golangci-lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare helm env
        id: fetch-helm-vars
        run: |
            chmod 700 .github/tools_install.sh
            ./.github/tools_install.sh
      
      - name: Package and Push Chart to ChartMuseum
        run: |
            IN=$(echo ${GITHUB_REPOSITORY})
            NAME=${IN#"Ubivius/"}
            VERSION=$(yq e '.version' ./chart/Chart.yaml)
            FULL_NAME="./${NAME}-${VERSION}.tgz"
            helm package chart/
            helm cm-push $FULL_NAME ysma500 -f
            helm repo update

  deployment-lke:
    needs: [publish-docker, publish-helm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare deploy env
        run: |
            chmod 700 .github/tools_install.sh
            ./.github/tools_install.sh
            curl -H "Authorization: Bearer ${{ env.LKE_SERVICEACCOUNT_TOKEN }}" https://api.linode.com/v4/lke/clusters/${{ env.LKE_CLUSTERID }}/kubeconfig | jq '.kubeconfig' | sed 's/["]//g' | base64 --decode > ~/.kube/config

      - name: Push with valuefile
        run: |
            IN=$(echo ${GITHUB_REPOSITORY})
            NAME=${IN#"Ubivius/"}
            VERSION=$(yq e '.version' ./chart/Chart.yaml)
            helm upgrade $NAME --install --version $VERSION ysma500/$NAME -f chart/values.yaml
